name: crocus
channels:
  - conda-forge
  - defaults
  - pyviz
dependencies:
  - python=3.11
  - arm_pyart
  - act-atmos
  - matplotlib
  - jupyterlab
  - cartopy
  - numpy
  - dask
  - distributed
  - xarray
  - pandas
  - fiona
  - hvplot
  - imageio
  - siphon
  - scikit-learn
  - cfgrib
  - geopandas
  - cmweather
  - great_tables
  - polars
  - Pillow
  - pip
  - pip:
    - selenium
    - ambient-api
    - sage-data-client
    - nexradaws
    - php
